services:
  redis:
    image: "redis:7"
    container_name: tt-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tt-api
    env_file:
      - .env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --proxy-headers
      --forwarded-allow-ips=*
      --reload
    volumes:
      - ./:/app
      # keep these in sync with HF_HOME + torch cache
      - hf-cache:/data/hf
      - torch-cache:/data/torch
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8000/healthz | grep -q 'ok'"]
      interval: 10s
      timeout: 5s
      retries: 10

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tt-worker
    env_file:
      - .env
    command: >
      celery -A app.workers.celery_app.celery_app
      worker
      -Q ${CELERY_TAGGING_QUEUE}
      -l INFO
      --concurrency=2
      --prefetch-multiplier=1
    volumes:
      - ./:/app
      - hf-cache:/data/hf
      - torch-cache:/data/torch
    depends_on:
      redis:
        condition: service_healthy

volumes:
  hf-cache:
  torch-cache:
