[tool.ruff]
line-length = 120
line.extend-select = ["E", "F", "I", "UP"]
exclude = ["venv", ".venv", "build", "dist"]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
