name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget
      
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Lint (ruff)
        run: ruff check .

      - name: Type check (mypy)
        run: mypy app || true
      
      - name: Run tests
        env:
          CELERY_TASK_ALWAYS_EAGER: "true"
          CELERY_TASK_EAGER_PROPAGATES: "true"
          REDIS_URL: "redis://localhost:6379/0"
          CACHE_TTL_SECONDS: "60"
          CELERY_TAGGING_QUEUE: "tagging"
          CACHE_NS: "ci"
          PYTHONPATH: "./"
        run: |
          pytest -q
